set(FOLDER_NAME "services")

if(NOT DEFINED OPENEMBER_SERVICE_OTA_AGENT OR OPENEMBER_SERVICE_OTA_AGENT)
    add_subdirectory(ota_agent)
endif()

if(NOT DEFINED OPENEMBER_SERVICE_WEB_CONSOLE OR OPENEMBER_SERVICE_WEB_CONSOLE)
    add_subdirectory(web_console)
endif()

if(NOT DEFINED OPENEMBER_SERVICE_LOGGER OR OPENEMBER_SERVICE_LOGGER)
    add_subdirectory(logger)
endif()

if(OPENEMBER_ENABLE_LINK AND OPENEMBER_ENABLE_MSGS
        AND (NOT DEFINED OPENEMBER_COMPONENT_SENSOR OR OPENEMBER_COMPONENT_SENSOR)
        AND (NOT DEFINED OPENEMBER_SERVICE_HARDWARE_INTERFACE OR OPENEMBER_SERVICE_HARDWARE_INTERFACE))
    add_subdirectory(hardware_interface)
endif()
