project(openember_hardware VERSION 0.1.0 LANGUAGES CXX)

set(OPENEMBER_HARDWARE_SRCS
    src/error.cpp
)

OPENEMBER_ADD_STATIC_LIBRARY(TARGET ${PROJECT_NAME}
    SRCS     ${OPENEMBER_HARDWARE_SRCS}
    LIBS     ${OPENEMBER_EXTERNAL_LIBRARIES}
    INCLUDES ${OPENEMBER_INCLUDE_DIRS} ${CMAKE_CURRENT_SOURCE_DIR}/include
    DESTINATION lib
)

add_library(openember::hardware ALIAS ${PROJECT_NAME})

set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 17)
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD_REQUIRED ON)
