#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="${1:-build-kconfig}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

CONFIG_FILE="${BUILD_DIR}/.config"
if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "Missing ${CONFIG_FILE}. Run menuconfig first." >&2
  exit 1
fi

backend=""
backend="$(awk '
  BEGIN { b="ZLOG" }
  /^CONFIG_OPENEMBER_LOG_BACKEND_SPDLOG=y/ { b="SPDLOG" }
  /^CONFIG_OPENEMBER_LOG_BACKEND_BUILTIN=y/ { b="BUILTIN" }
  END { print b }
' "${CONFIG_FILE}")"

tp_mode="$(awk '
  BEGIN { m="FETCH" }
  /^CONFIG_OPENEMBER_TP_MODE_VENDOR=y/ { m="VENDOR" }
  /^CONFIG_OPENEMBER_TP_MODE_SYSTEM=y/ { m="SYSTEM" }
  END { print m }
' "${CONFIG_FILE}")"

json_lib="$(awk '
  BEGIN { j="CJSON" }
  /^CONFIG_OPENEMBER_JSON_LIBRARY_NLOHMANN=y/ { j="NLOHMANN_JSON" }
  END { print j }
' "${CONFIG_FILE}")"

pubsub_backend="$(awk '
  BEGIN { b="ZMQ" }
  /^CONFIG_OPENEMBER_PUBSUB_BACKEND_NNG=y/ { b="NNG" }
  /^CONFIG_OPENEMBER_PUBSUB_BACKEND_LCM=y/ { b="LCM" }
  END { print b }
' "${CONFIG_FILE}")"

msgbus_backend="$(awk '
  BEGIN { b="NNG" }
  /^CONFIG_OPENEMBER_MSGBUS_BACKEND_LCM=y/ { b="LCM" }
  END { print b }
' "${CONFIG_FILE}")"

onoff() {
  local sym="$1"
  if grep -q "^${sym}=y" "${CONFIG_FILE}"; then
    echo ON
  else
    echo OFF
  fi
}

tests_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_TESTS)"
examples_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_EXAMPLES)"
openmp_enabled="$(onoff CONFIG_OPENEMBER_ENABLE_OPENMP)"
debug_enabled="$(onoff CONFIG_OPENEMBER_DEBUG_ENABLED)"
opt_disabled="$(onoff CONFIG_OPENEMBER_OPTIMIZATION_DISABLED)"
crosscompile_enabled="$(onoff CONFIG_OPENEMBER_CROSSCOMPILE_ENABLED)"
use_yamlcpp="$(onoff CONFIG_OPENEMBER_USE_YAMLCPP)"
use_asio="$(onoff CONFIG_OPENEMBER_USE_ASIO)"
module_template="$(onoff CONFIG_OPENEMBER_MODULE_TEMPLATE)"
module_alogd="$(onoff CONFIG_OPENEMBER_MODULE_ALOGD)"
module_device_manager="$(onoff CONFIG_OPENEMBER_MODULE_DEVICE_MANAGER)"
module_message_dispatcher="$(onoff CONFIG_OPENEMBER_MODULE_MESSAGE_DISPATCHER)"
module_config_manager="$(onoff CONFIG_OPENEMBER_MODULE_CONFIG_MANAGER)"
module_monitor_alarm="$(onoff CONFIG_OPENEMBER_MODULE_MONITOR_ALARM)"
module_ota="$(onoff CONFIG_OPENEMBER_MODULE_OTA)"
module_acquisition="$(onoff CONFIG_OPENEMBER_MODULE_ACQUISITION)"
module_web_server="$(onoff CONFIG_OPENEMBER_MODULE_WEB_SERVER)"
feature_algorithm="$(onoff CONFIG_OPENEMBER_FEATURE_ALGORITHM)"

log_file="/etc/openember/zlog.conf"
log_file="$(awk '
  /^CONFIG_OPENEMBER_LOG_FILE=/ {
    v=$0
    sub(/^CONFIG_OPENEMBER_LOG_FILE=/,"",v)
    gsub(/^"/,"",v); gsub(/"$/,"",v)
    print v
    exit
  }
' "${CONFIG_FILE}")"
if [[ -z "${log_file}" ]]; then
  log_file="/etc/openember/zlog.conf"
fi

out_cmake="${BUILD_DIR}/config.cmake"
cat > "${out_cmake}" <<EOF
# Auto-generated by scripts/kconfig/genconfig.sh
# Source: ${CONFIG_FILE}

set(OPENEMBER_LOG_BACKEND "${backend}" CACHE STRING "OpenEmber logging backend" FORCE)
set(OPENEMBER_LOG_FILE "${log_file}" CACHE STRING "zlog.conf path" FORCE)
set(OPENEMBER_THIRD_PARTY_MODE "${tp_mode}" CACHE STRING "Third-party source mode: FETCH/VENDOR/SYSTEM" FORCE)
set(OPENEMBER_JSON_LIBRARY "${json_lib}" CACHE STRING "JSON implementation for OpenEmber" FORCE)
set(OPENEMBER_WITH_YAMLCPP ${use_yamlcpp} CACHE BOOL "Fetch/use yaml-cpp (optional C++ dependency)" FORCE)
set(OPENEMBER_WITH_ASIO ${use_asio} CACHE BOOL "Fetch/use standalone Asio (optional)" FORCE)

set(TESTS_ENABLED ${tests_enabled} CACHE BOOL "Whether to unit test" FORCE)
set(EXAMPLES_ENABLED ${examples_enabled} CACHE BOOL "Whether compile examples" FORCE)
set(OPENMP_ENABLED ${openmp_enabled} CACHE BOOL "Whether to enable omp feature" FORCE)
set(DEBUG_ENABLED ${debug_enabled} CACHE BOOL "Whether to enable debug mode" FORCE)
set(OPTIMIZATION_DISABLED ${opt_disabled} CACHE BOOL "Whether to disable optimization" FORCE)
set(CROSSCOMPILE_ENABLED ${crosscompile_enabled} CACHE BOOL "Whether to build for ARM" FORCE)

set(OPENEMBER_MODULE_TEMPLATE ${module_template} CACHE BOOL "Build module Template" FORCE)
set(OPENEMBER_MODULE_ALOGD ${module_alogd} CACHE BOOL "Build module Alogd" FORCE)
set(OPENEMBER_MODULE_DEVICE_MANAGER ${module_device_manager} CACHE BOOL "Build module DeviceManager" FORCE)
set(OPENEMBER_MODULE_MESSAGE_DISPATCHER ${module_message_dispatcher} CACHE BOOL "Build module MessageDispatcher" FORCE)
set(OPENEMBER_MODULE_CONFIG_MANAGER ${module_config_manager} CACHE BOOL "Build module ConfigManager" FORCE)
set(OPENEMBER_MODULE_MONITOR_ALARM ${module_monitor_alarm} CACHE BOOL "Build module MonitorAlarm" FORCE)
set(OPENEMBER_MODULE_OTA ${module_ota} CACHE BOOL "Build module OTA" FORCE)
set(OPENEMBER_MODULE_ACQUISITION ${module_acquisition} CACHE BOOL "Build module Acquisition" FORCE)
set(OPENEMBER_MODULE_WEB_SERVER ${module_web_server} CACHE BOOL "Build module WebServer" FORCE)
set(OPENEMBER_FEATURE_ALGORITHM ${feature_algorithm} CACHE BOOL "Enable Algorithm module" FORCE)

# Keep existing CMake backend selection interface
set(BUILD_PUBSUB_ZMQ OFF CACHE BOOL "" FORCE)
set(BUILD_PUBSUB_NNG OFF CACHE BOOL "" FORCE)
set(BUILD_PUBSUB_LCM OFF CACHE BOOL "" FORCE)
if("${pubsub_backend}" STREQUAL "ZMQ")
  set(BUILD_PUBSUB_ZMQ ON CACHE BOOL "" FORCE)
elseif("${pubsub_backend}" STREQUAL "NNG")
  set(BUILD_PUBSUB_NNG ON CACHE BOOL "" FORCE)
elseif("${pubsub_backend}" STREQUAL "LCM")
  set(BUILD_PUBSUB_LCM ON CACHE BOOL "" FORCE)
endif()

if("${msgbus_backend}" STREQUAL "LCM")
  set(OPENEMBER_MSGBUS_USE_NNG OFF CACHE BOOL "Use NNG backend for internal msgbus" FORCE)
  set(OPENEMBER_MSGBUS_USE_LCM ON CACHE BOOL "Use LCM backend for internal msgbus" FORCE)
else()
  set(OPENEMBER_MSGBUS_USE_NNG ON CACHE BOOL "Use NNG backend for internal msgbus" FORCE)
  set(OPENEMBER_MSGBUS_USE_LCM OFF CACHE BOOL "Use LCM backend for internal msgbus" FORCE)
endif()
EOF

echo "Generated: ${out_cmake}" >&2

