# openember-msgs (https://github.com/openember/openember-msgs)
#
# Protocol definitions shared by OpenEmber and EmberLite. OpenEmber uses the
# C++ protobuf target generated by the protocol repository itself.

include(${CMAKE_SOURCE_DIR}/cmake/ThirdPartyArchive.cmake)

function(openember_prepare_openember_msgs_fetch out_var)
    if(OPENEMBER_THIRD_PARTY_MODE STREQUAL "FETCH")
        set(_deps_parent "${CMAKE_BINARY_DIR}/_deps")
        set(_stage "${_deps_parent}/${OPENEMBER_MSGS_STAGE_DIR_NAME}")

        file(MAKE_DIRECTORY "${_deps_parent}")
        openember_third_party_cache_dir(_cache)
        openember_third_party_download_to_cache_key(
            "${OPENEMBER_MSGS_URL}" "${_cache}" "${OPENEMBER_MSGS_CACHE_KEY}" _archive)

        file(REMOVE_RECURSE "${_stage}")
        message(STATUS "Third-party: extracting ${_archive} -> ${_deps_parent}")
        openember_third_party_extract_archive("${_archive}" "${_deps_parent}")
        if(NOT EXISTS "${_stage}/CMakeLists.txt")
            message(FATAL_ERROR
                "After extract, expected ${_stage}/CMakeLists.txt "
                "(check OPENEMBER_MSGS_REF / OPENEMBER_MSGS_URL).")
        endif()

        set(${out_var} "${_stage}" PARENT_SCOPE)
        return()
    endif()

    openember_third_party_prepare_stage(_src "${OPENEMBER_MSGS_CACHE_KEY}" "${OPENEMBER_MSGS_STAGE_DIR_NAME}"
        "${OPENEMBER_MSGS_URL}" "CMakeLists.txt" "")
    set(${out_var} "${_src}" PARENT_SCOPE)
endfunction()

function(openember_prepare_openember_msgs_source out_var)
    if(NOT (OPENEMBER_MSGS_SOURCE STREQUAL "FETCH") AND NOT (OPENEMBER_MSGS_SOURCE STREQUAL "LOCAL"))
        message(FATAL_ERROR "OPENEMBER_MSGS_SOURCE must be FETCH or LOCAL (got '${OPENEMBER_MSGS_SOURCE}')")
    endif()

    if(OPENEMBER_MSGS_SOURCE STREQUAL "LOCAL")
        if(NOT OPENEMBER_MSGS_LOCAL_SOURCE)
            message(FATAL_ERROR
                "OPENEMBER_MSGS_SOURCE=LOCAL requires OPENEMBER_MSGS_LOCAL_SOURCE "
                "to be an absolute path to openember-msgs.")
        endif()
        if(NOT IS_ABSOLUTE "${OPENEMBER_MSGS_LOCAL_SOURCE}")
            message(FATAL_ERROR "OPENEMBER_MSGS_LOCAL_SOURCE must be absolute: ${OPENEMBER_MSGS_LOCAL_SOURCE}")
        endif()
        if(NOT EXISTS "${OPENEMBER_MSGS_LOCAL_SOURCE}/CMakeLists.txt")
            message(FATAL_ERROR "Expected CMakeLists.txt under OPENEMBER_MSGS_LOCAL_SOURCE=${OPENEMBER_MSGS_LOCAL_SOURCE}")
        endif()
        set(_src "${OPENEMBER_MSGS_LOCAL_SOURCE}")
        message(STATUS "openember-msgs: using local checkout ${_src}")
    else()
        openember_prepare_openember_msgs_fetch(_src)
        message(STATUS "openember-msgs: fetched ${OPENEMBER_MSGS_REF} -> ${_src}")
    endif()

    set(${out_var} "${_src}" PARENT_SCOPE)
endfunction()

function(openember_get_openember_msgs)
    if(TARGET openember::msgs_cpp OR TARGET openember_msgs_cpp)
        return()
    endif()

    openember_prepare_openember_msgs_source(_src)

    set(OPENEMBER_MSGS_BUILD_CPP ON CACHE BOOL "Generate and build C++ protobuf bindings" FORCE)
    set(_build_dir "${CMAKE_BINARY_DIR}/_deps/${OPENEMBER_MSGS_STAGE_DIR_NAME}-build")
    file(REMOVE_RECURSE "${_build_dir}")
    add_subdirectory("${_src}" "${_build_dir}")

    if(NOT TARGET openember::msgs_cpp)
        message(FATAL_ERROR "openember-msgs: expected target openember::msgs_cpp after add_subdirectory")
    endif()

    set(OPENEMBER_MSGS_LIBRARIES openember::msgs_cpp PARENT_SCOPE)
endfunction()
