# paho.mqtt.c：third_party/ 归档缓存 + 解压到 build/_deps/paho.mqtt.c-<version>/
#
# 不再使用 FetchContent 工程名（避免出现 openember_* 与上游不一致的 -src 目录名）。

include(${CMAKE_SOURCE_DIR}/cmake/ThirdPartyArchive.cmake)

function(openember_get_paho_mqtt_c)
    set(_bind "${CMAKE_BINARY_DIR}/_deps/${OPENEMBER_PAHO_MQTT_C_STAGE_DIR_NAME}-build")

    # OPENEMBER_MQTT_PAHO_TLS: Kconfig / cache — OFF 强制无 TLS；ON 强制需要 OpenSSL；未定义则尽量自动检测
    if(DEFINED OPENEMBER_MQTT_PAHO_TLS AND NOT OPENEMBER_MQTT_PAHO_TLS)
        set(PAHO_WITH_SSL OFF CACHE BOOL "Enable SSL for paho" FORCE)
        message(STATUS "Paho MQTT C: TLS disabled (OPENEMBER_MQTT_PAHO_TLS=OFF)")
    elseif(DEFINED OPENEMBER_MQTT_PAHO_TLS AND OPENEMBER_MQTT_PAHO_TLS)
        find_package(OpenSSL REQUIRED)
        set(PAHO_WITH_SSL ON CACHE BOOL "Enable SSL for paho" FORCE)
    else()
        find_package(OpenSSL QUIET)
        if(OpenSSL_FOUND)
            set(PAHO_WITH_SSL ON CACHE BOOL "Enable SSL for paho" FORCE)
        else()
            set(PAHO_WITH_SSL OFF CACHE BOOL "Enable SSL for paho" FORCE)
            message(WARNING "OpenSSL not found (install libssl-dev / openssl-devel). Paho builds without TLS; use tcp:// only or install OpenSSL for ssl:// (e.g. EMQX Cloud :8883).")
        endif()
    endif()

    set(PAHO_MQTT_C_INCLUDE_DIRS "" PARENT_SCOPE)
    set(PAHO_MQTT_C_LIBRARIES "" PARENT_SCOPE)

    if(PAHO_MQTT_C_LOCAL_SOURCE)
        message(STATUS "Paho MQTT C: using PAHO_MQTT_C_LOCAL_SOURCE=${PAHO_MQTT_C_LOCAL_SOURCE}")
        set(_src "${PAHO_MQTT_C_LOCAL_SOURCE}")
    else()
        openember_third_party_prepare_stage(_src "${OPENEMBER_PAHO_MQTT_C_CACHE_KEY}" "${OPENEMBER_PAHO_MQTT_C_STAGE_DIR_NAME}"
            "${OPENEMBER_PAHO_MQTT_C_URL}" "CMakeLists.txt" "")
    endif()

    set(PAHO_ENABLE_TESTING OFF CACHE BOOL "Build paho unit tests" FORCE)
    set(PAHO_ENABLE_CPACK OFF CACHE BOOL "Build paho cpack" FORCE)
    set(PAHO_BUILD_SHARED OFF CACHE BOOL "Build shared libs" FORCE)
    set(PAHO_BUILD_STATIC ON CACHE BOOL "Build static libs" FORCE)
    set(PAHO_BUILD_DOCUMENTATION OFF CACHE BOOL "Disable docs" FORCE)
    set(PAHO_BUILD_SAMPLES OFF CACHE BOOL "Disable samples" FORCE)

    add_subdirectory("${_src}" "${_bind}")

    set(_paho_fc_source_dir "${_src}")

    # Provide stable alias targets for easier future migration.
    if(TARGET paho-mqtt3cs AND NOT TARGET paho_mqtt_c::paho-mqtt3cs)
        add_library(paho_mqtt_c::paho-mqtt3cs ALIAS paho-mqtt3cs)
    endif()
    if(TARGET paho-mqtt3as AND NOT TARGET paho_mqtt_c::paho-mqtt3as)
        add_library(paho_mqtt_c::paho-mqtt3as ALIAS paho-mqtt3as)
    endif()
    if(TARGET paho-mqtt3c AND NOT TARGET paho_mqtt_c::paho-mqtt3c)
        add_library(paho_mqtt_c::paho-mqtt3c ALIAS paho-mqtt3c)
    endif()
    if(TARGET paho-mqtt3a AND NOT TARGET paho_mqtt_c::paho-mqtt3a)
        add_library(paho_mqtt_c::paho-mqtt3a ALIAS paho-mqtt3a)
    endif()

    if(TARGET paho-mqtt3cs-static AND NOT TARGET paho_mqtt_c::paho-mqtt3cs-static)
        add_library(paho_mqtt_c::paho-mqtt3cs-static ALIAS paho-mqtt3cs-static)
    endif()
    if(TARGET paho-mqtt3as-static AND NOT TARGET paho_mqtt_c::paho-mqtt3as-static)
        add_library(paho_mqtt_c::paho-mqtt3as-static ALIAS paho-mqtt3as-static)
    endif()
    if(TARGET paho-mqtt3c-static AND NOT TARGET paho_mqtt_c::paho-mqtt3c-static)
        add_library(paho_mqtt_c::paho-mqtt3c-static ALIAS paho-mqtt3c-static)
    endif()
    if(TARGET paho-mqtt3a-static AND NOT TARGET paho_mqtt_c::paho-mqtt3a-static)
        add_library(paho_mqtt_c::paho-mqtt3a-static ALIAS paho-mqtt3a-static)
    endif()

    set(PAHO_MQTT_C_INCLUDE_DIRS ${_paho_fc_source_dir}/src PARENT_SCOPE)

    if(DEFINED OPENEMBER_MQTT_PAHO_ASYNC AND OPENEMBER_MQTT_PAHO_ASYNC)
        set(_paho_link_async ON)
    else()
        set(_paho_link_async OFF)
    endif()

    if(_paho_link_async)
        if(TARGET paho-mqtt3as-static AND TARGET paho-mqtt3cs-static)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3as-static paho-mqtt3cs-static PARENT_SCOPE)
        elseif(TARGET paho-mqtt3as AND TARGET paho-mqtt3cs)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3as paho-mqtt3cs PARENT_SCOPE)
        elseif(TARGET paho-mqtt3a-static AND TARGET paho-mqtt3c-static)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3a-static paho-mqtt3c-static PARENT_SCOPE)
        elseif(TARGET paho-mqtt3a AND TARGET paho-mqtt3c)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3a paho-mqtt3c PARENT_SCOPE)
        else()
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3a paho-mqtt3c PARENT_SCOPE)
        endif()
    else()
        if(TARGET paho-mqtt3cs-static)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3cs-static PARENT_SCOPE)
        elseif(TARGET paho-mqtt3cs)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3cs PARENT_SCOPE)
        elseif(TARGET paho-mqtt3c-static)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3c-static PARENT_SCOPE)
        elseif(TARGET paho-mqtt3c)
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3c PARENT_SCOPE)
        else()
            set(PAHO_MQTT_C_LIBRARIES paho-mqtt3c PARENT_SCOPE)
        endif()
    endif()
endfunction()
